# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pfLjGfy65FuWCBq054kDf-XwQ6FcRTn0
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# %matplotlib inline

df = pd.read_excel('/content/bus.xlsx')

df

plt.scatter(df['경도'],df['위도'])

df

df[df['정류소명'] == '(구)중앙파출소']

df.tail()

df2 = pd.read_excel('/content/mountain.xlsx')

df2

df2.groupby('어리목').sum()

df2['어리목'].sum()

df2['총합'] = None
for i in range (len(df2)):
  df2['총합'].iloc[i] = df2.drop('구분',axis=1).iloc[i].sum()

df2.iloc[:,0]



"""숙제: 마지막 열에 한 날짜 넣고, 각 행의 값들을 각각 더해서 한 값을 넣기"""

df3 = pd.read_csv('/content/hadoop.csv')

len(df3['access_ip'].unique())

unique_ip = df3['access_ip'].unique()

unique_ip

unique_dict = dict.fromkeys(unique_ip)
for i in unique_dict.keys():
  unique_dict[i] = []

unique_dict

for i in range(len(df3)):
  for j in unique_dict.keys():
    if(j == df3['access_ip'].iloc[i]):
      key = j
      unique_dict[key].append(df3['item_name'].iloc[i])

pd.Dataframe.from_dict(unique_dict,orient='index')

